apiVersion: v1
kind: Namespace
metadata:
  name: chaos-framework
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chaos-framework
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: iskorotkov/chaos-frontend:v0.3.1
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chaos-framework
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
